version: "3.8"
services:
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: >
      /bin/sh -c "chmod +x /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cruddb
    volumes:
      - db_data:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # << NECESARIO para ejecutar Docker desde Jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  db_data:
  jenkins_data:
