version: "3.8"
services:
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: >
      /bin/sh -c "chmod +x /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cruddb
    volumes:
      - db_data:/var/lib/mysql

  jenkins:
    build: ./jenkins  # Apunta al Dockerfile que creaste para Jenkins
    user: root        # Le da permisos root para instalar Docker y Docker Compose
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"  # Puerto para agentes de Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Monta el socket de Docker
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  db_data:
  jenkins_data:
